{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"amostra_bolsa\",\"dim_regioes\",\"dim_usuarios_rls\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_ed85260c-17ef-422b-b004-7ee0a2d2f8ca",
        "fromColumn": "UF",
        "fromTable": "amostra_bolsa",
        "toColumn": "UF",
        "toTable": "dim_regioes"
      },
      {
        "name": "5bf6acc4-f2f2-ebc1-d08d-23eaa8d6f8c7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "UF",
        "fromTable": "dim_regioes",
        "toColumn": "regiao_permitida",
        "toTable": "dim_usuarios_rls"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "amostra_bolsa",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcf8f622-2905-44da-b3d1-ebd5c214d8c9",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "CÓDIGO MUNICÍPIO SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af773dda-d461-4a14-81ca-0424e7c5b070",
            "sourceColumn": "CÓDIGO MUNICÍPIO SIAFI",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME MUNICÍPIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0244fd1-8d60-424a-872f-f99950c99688",
            "sourceColumn": "NOME MUNICÍPIO",
            "summarizeBy": "none"
          },
          {
            "name": "CPF FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e954cbe9-a959-4f23-a1b0-b1b4b00d1d1c",
            "sourceColumn": "CPF FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "NIS FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e53d52f-4d43-4599-8a97-7d6eab2035d8",
            "sourceColumn": "NIS FAVORECIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b6394ab-f25d-4fbc-88fd-10aff368ef14",
            "sourceColumn": "NOME FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR PARCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "d9d9de0b-d5cb-44fb-b22d-7f168ddd6281",
            "sourceColumn": "VALOR PARCELA",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO COMPETÊNCIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec75a5fa-3a27-44e4-9f2b-e8f4ca21d0d3",
            "sourceColumn": "ANO COMPETÊNCIA",
            "summarizeBy": "sum"
          },
          {
            "name": "MÊS COMPETÊNCIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "63b165ce-21e5-456e-b8dd-bae515b76b6f",
            "sourceColumn": "MÊS COMPETÊNCIA",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b0675ae2-0a93-4b0a-ba0a-df090b51b358",
        "measures": [
          {
            "name": "Total Repasse",
            "expression": "SUM(amostra_bolsa[VALOR PARCELA])",
            "formatString": "0",
            "lineageTag": "99a7a11a-528c-406e-85aa-ad0d7ff779c8"
          },
          {
            "name": "Total de Beneficiários",
            "expression": "COUNT(amostra_bolsa[NIS FAVORECIDO])",
            "formatString": "0",
            "lineageTag": "adece530-9c2f-47ab-a6d8-e20ce2260ae7"
          },
          {
            "name": "Ticket Médio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(amostra_bolsa[VALOR PARCELA])",
            "lineageTag": "2e9a4348-6910-4601-9dfa-489f9cfe44b1"
          },
          {
            "name": "Municípios Atendidos",
            "expression": "DISTINCTCOUNT(amostra_bolsa[CÓDIGO MUNICÍPIO SIAFI])",
            "formatString": "0",
            "lineageTag": "c49d6ae8-4111-4c02-8415-cd3c5fbf0038"
          }
        ],
        "partitions": [
          {
            "name": "amostra_bolsa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\lucas.patriota\\Documents\\bolsafamilia-rls\\amostra_bolsa.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"MÊS COMPETÊNCIA\", Int64.Type}, {\"UF\", type text}, {\"CÓDIGO MUNICÍPIO SIAFI\", Int64.Type}, {\"NOME MUNICÍPIO\", type text}, {\"CPF FAVORECIDO\", type text}, {\"NIS FAVORECIDO\", Int64.Type}, {\"NOME FAVORECIDO\", type text}, {\"VALOR PARCELA\", Currency.Type}}),",
                "    #\"Dividir Coluna pela Posição\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Tipo Alterado\", {{\"MÊS COMPETÊNCIA\", type text}}, \"pt-BR\"), \"MÊS COMPETÊNCIA\", Splitter.SplitTextByRepeatedLengths(4), {\"MÊS COMPETÊNCIA.1\", \"MÊS COMPETÊNCIA.2\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Dividir Coluna pela Posição\",{{\"MÊS COMPETÊNCIA.1\", \"ANO COMPETÊNCIA\"}, {\"MÊS COMPETÊNCIA.2\", \"MÊS COMPETÊNCIA\"}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"ANO COMPETÊNCIA\", type date}}),",
                "    #\"Ano Extraído\" = Table.TransformColumns(#\"Tipo Alterado1\",{{\"ANO COMPETÊNCIA\", Date.Year, Int64.Type}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Ano Extraído\",\"01\",\"1\",Replacer.ReplaceText,{\"MÊS COMPETÊNCIA\"}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"MÊS COMPETÊNCIA\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9281f4b0-861b-4c3b-a316-ec833dc71fe0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9a659e05-a246-4f9d-8a13-04b960f88ab7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cb43d432-1a49-4bb3-8fb7-e2a9b8dd32f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "02e3de56-3158-42fb-8676-d88c320528f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "63fab364-db52-42e7-8440-18402bd6f60b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "36ebfc40-2384-4d02-a179-dd72519e9210",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "94d6c976-7d80-4a75-aefd-0e56555e9ad2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "37e4753e-ef21-4ff3-8bc7-d03f14c694c5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "b8f81680-35db-4d18-952e-8c5ba3726946",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ea6957b9-8184-4d9e-ac04-a7a8629ea945",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "ca2593bd-7dac-49a3-bf71-ac1fd2d45c34",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "40ea21c5-f6e8-4256-a90d-c4ccc9d164f4",
                "ordinal": 3
              }
            ],
            "lineageTag": "587df7ff-7444-4409-b266-d02f304a0be3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "88b040bc-38bd-47fb-bafd-cb5d1186baba",
        "partitions": [
          {
            "name": "DateTableTemplate_9281f4b0-861b-4c3b-a316-ec833dc71fe0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_regioes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4377e9b2-2bf5-41c8-b2f4-4233ee7368e9",
            "sourceColumn": "Regiao",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "946ffd50-e35c-41d2-ba3b-23212c556e2b",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0058d0b5-9434-4135-9b38-27b4799dcb88",
        "partitions": [
          {
            "name": "dim_regioes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "Fonte = Table.FromRows(",
                "{",
                "{\"Norte\", \"AC\"},",
                "{\"Norte\", \"AM\"},",
                "{\"Norte\", \"AP\"},",
                "{\"Norte\", \"PA\"},",
                "{\"Norte\", \"RO\"},",
                "{\"Norte\", \"RR\"},",
                "{\"Norte\", \"TO\"},",
                "{\"Nordeste\", \"AL\"},",
                "{\"Nordeste\", \"BA\"},",
                "{\"Nordeste\", \"CE\"},",
                "{\"Nordeste\", \"MA\"},",
                "{\"Nordeste\", \"PB\"},",
                "{\"Nordeste\", \"PE\"},",
                "{\"Nordeste\", \"PI\"},",
                "{\"Nordeste\", \"RN\"},",
                "{\"Nordeste\", \"SE\"},",
                "{\"Centro-Oeste\", \"DF\"},",
                "{\"Centro-Oeste\", \"GO\"},",
                "{\"Centro-Oeste\", \"MS\"},",
                "{\"Centro-Oeste\", \"MT\"},",
                "{\"Sudeste\", \"ES\"},",
                "{\"Sudeste\", \"MG\"},",
                "{\"Sudeste\", \"RJ\"},",
                "{\"Sudeste\", \"SP\"},",
                "{\"Sul\", \"PR\"},",
                "{\"Sul\", \"RS\"},",
                "{\"Sul\", \"SC\"}",
                "},",
                "{\"Regiao\", \"UF\"}",
                "),",
                "TipoAlterado = Table.TransformColumnTypes(",
                "Fonte,",
                "{",
                "{\"Regiao\", type text},",
                "{\"UF\", type text}",
                "}",
                ")",
                "in",
                "TipoAlterado"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_usuarios_rls",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "email_usuario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a24f37e-a5c9-4a78-a5d8-dc47ea1f2e6f",
            "sourceColumn": "email_usuario",
            "summarizeBy": "none"
          },
          {
            "name": "regiao_permitida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab37193d-bb95-4006-9035-ae42d706c22c",
            "sourceColumn": "regiao_permitida",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56f2beb4-d0df-42fc-968b-adc53b94eb23",
        "partitions": [
          {
            "name": "dim_usuarios_rls",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "Fonte = Table.FromRows(",
                "{",
                "{\"gestor.norte@ministerio.br\", \"Norte\"},",
                "{\"gestor.nordeste@ministerio.br\", \"Nordeste\"},",
                "{\"gestor.centroeste@ministerio.br\", \"Centro-Oeste\"},",
                "{\"gestor.sudeste@ministerio.br\", \"Sudeste\"},",
                "{\"gestor.sul@ministerio.br\", \"Sul\"}",
                "},",
                "{\"email_usuario\", \"regiao_permitida\"}",
                "),",
                "TipoAlterado = Table.TransformColumnTypes(",
                "Fonte,",
                "{",
                "{\"email_usuario\", type text},",
                "{\"regiao_permitida\", type text}",
                "}",
                ")",
                "in",
                "TipoAlterado"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}